// ------------------------------------------------------------------------------
//  <autogenerated>
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Castle.Components.Binder 3.2.2 for .NETFramework v4.5")]
[assembly: System.Reflection.AssemblyDescription("Castle.Components.Binder 3.2.2 for .NETFramework v4.5")]
[assembly: System.Reflection.AssemblyProduct("Castle.Components.Binder")]
[assembly: System.Reflection.AssemblyVersion("3.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.2.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.2.2.0")]
